### ISSUE TITLE
Working with TensorRT 4?

### ISSUE THREAD

**Issue by GustavZ** [NVIDIA-Jetson/tf_to_trt_image_classification#10]
Does this project also work with the newer Version of TensorRT 4.0 RC?

**Comment by jaybdub-nv** [comment]
This project works with TensorRT 3.0.4 that ships with the latest JetPack 3.2.  As mentioned [here](https://devtalk.nvidia.com/default/topic/1031806/tensorrt-4-0-on-tx2-/?offset=4), TensorRT 4.0 RC is not currently available for Jetson.

If you are using desktop you may be able to try TensorRT 4.0 RC, but this project has not been tested against that configuration.

**Comment by GustavZ** [comment]
Alright thank you.
Another Question: are there also Detection Models for TensorRT available?
