### ISSUE TITLE
Tensorflow Python3 Support?

### ISSUE THREAD

**Issue by kuonangzhe** [NVIDIA-Jetson/tf_to_trt_image_classification#15]
Hi, is there support for tensorflow in python3?

**Comment by jaybdub-nv** [comment]
Hi kuonangzhe.

You may download the pre-built TensorFlow 1.7 pip wheels from here.

https://devtalk.nvidia.com/default/topic/1031300/jetson-tx2/tensorflow-1-7-wheel-with-jetpack-3-2-/

This includes Python 3.5.
