### ISSUE TITLE
Wheel for TF 1.8?

### ISSUE THREAD

**Issue by alejandroandreu** [NVIDIA-Jetson/tf_to_trt_image_classification#20]
Did you build a wheel file for Tensorflow 1.8? Or if you didn't, which instructions did you follow?

**Comment by ds2268** [comment]
https://devtalk.nvidia.com/default/topic/1031300/jetson-tx2/tensorflow-1-8-wheel-with-jetpack-3-2-/1

**Comment by alejandroandreu** [comment]
Ok, thanks.
