### ISSUE TITLE
Could NOT find CUDA: Found unsuitable version "9.1", but required is exact   version "7.5"

### ISSUE THREAD

**Issue by groot-1313** [NVIDIA-Jetson/tf_to_trt_image_classification#8]
Upon running the `cmake` command, I encounter the following error:

> CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find CUDA: Found unsuitable version "9.1", but required is exact
  version "7.5" (found /usr/local/cuda)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindCUDA.cmake:949 (find_package_handle_standard_args)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:86 (find_package)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:105 (find_host_package)
  CMakeLists.txt:4 (find_package)

I have the Cuda 9.0 and 9.1 versions installed. I would prefer a workaround because I do not wish to install Cuda 7.5.

**Comment by jaybdub-nv** [comment]
This repository is currently targeting the Jetson TX2 configured with JetPack 3.2.  JetPack 3.2 installs CUDA 9.0 and cuDNN 7.0.5 and OpenCV for Tegra onto the TX2.

Building on a Desktop machine is not tested, but may be possible.  Judging from the call stack it looks like the version of OpenCV that you have installed is targeting CUDA 7.5.  You could possibly build OpenCV to target version 9.0 or 9.1 of CUDA if you do not wish to install another version of CUDA.
